In [1]:
import torch
import torch.nn as nn

In [2]:
sequence_length = 1
batch_size = 16
output_size = 3
target_size = 3

In [3]:
input = torch.rand(sequence_length, batch_size, output_size, requires_grad = True)
output = torch.empty(sequence_length, batch_size, target_size).random_(2)
m = nn.Sigmoid()
criterion = nn.BCELoss()

In [4]:
print(input.size())
print(input.dim())

torch.Size([1, 16, 3])
3


In [5]:
input

tensor([[[0.3752, 0.1386, 0.6633],
         [0.5925, 0.9046, 0.8070],
         [0.2641, 0.6145, 0.3108],
         [0.6835, 0.5369, 0.7257],
         [0.8978, 0.6765, 0.5452],
         [0.4437, 0.6287, 0.9803],
         [0.3486, 0.9815, 0.9027],
         [0.1579, 0.4482, 0.7365],
         [0.2054, 0.7987, 0.9141],
         [0.2318, 0.5451, 0.0202],
         [0.6431, 0.3513, 0.9418],
         [0.3910, 0.4686, 0.2150],
         [0.2547, 0.8702, 0.2313],
         [0.6424, 0.3359, 0.5872],
         [0.3646, 0.6248, 0.1698],
         [0.8950, 0.4742, 0.9803]]], requires_grad=True)

In [6]:
print(output.size())
print(output.dim())

torch.Size([1, 16, 3])
3


In [7]:
output

tensor([[[0., 1., 1.],
         [1., 0., 1.],
         [1., 1., 0.],
         [0., 1., 1.],
         [1., 0., 0.],
         [1., 0., 1.],
         [0., 1., 1.],
         [1., 0., 0.],
         [1., 1., 1.],
         [1., 0., 0.],
         [1., 1., 0.],
         [0., 0., 1.],
         [0., 0., 0.],
         [0., 0., 1.],
         [0., 0., 1.],
         [1., 1., 0.]]])

In [8]:
for index, sample in enumerate(zip(input[0], output[0])):
    i, o = sample
    loss = criterion(i, o)
    print(i)
    print(o)
    print(loss)
    print()
    loss.backward()

tensor([0.3752, 0.1386, 0.6633], grad_fn=<SelectBackward>)
tensor([0., 1., 1.])
tensor(0.9524, grad_fn=<BinaryCrossEntropyBackward>)

tensor([0.5925, 0.9046, 0.8070], grad_fn=<SelectBackward>)
tensor([1., 0., 1.])
tensor(1.0292, grad_fn=<BinaryCrossEntropyBackward>)

tensor([0.2641, 0.6145, 0.3108], grad_fn=<SelectBackward>)
tensor([1., 1., 0.])
tensor(0.7302, grad_fn=<BinaryCrossEntropyBackward>)

tensor([0.6835, 0.5369, 0.7257], grad_fn=<SelectBackward>)
tensor([0., 1., 1.])
tensor(0.6977, grad_fn=<BinaryCrossEntropyBackward>)

tensor([0.8978, 0.6765, 0.5452], grad_fn=<SelectBackward>)
tensor([1., 0., 0.])
tensor(0.6747, grad_fn=<BinaryCrossEntropyBackward>)

tensor([0.4437, 0.6287, 0.9803], grad_fn=<SelectBackward>)
tensor([1., 0., 1.])
tensor(0.6077, grad_fn=<BinaryCrossEntropyBackward>)

tensor([0.3486, 0.9815, 0.9027], grad_fn=<SelectBackward>)
tensor([0., 1., 1.])
tensor(0.1832, grad_fn=<BinaryCrossEntropyBackward>)

tensor([0.1579, 0.4482, 0.7365], grad_fn=<SelectBackward>)
ten