In [1]:
import torch
import torch.nn as nn

In [2]:
sequence_length = 1
batch_size = 16
output_size = 3
target_size = 3

In [3]:
input = torch.rand(sequence_length, batch_size, output_size, requires_grad = True)
output = torch.empty(sequence_length, batch_size, target_size).random_(2)
m = nn.Sigmoid()
criterion = nn.BCELoss()

In [4]:
print(input.size())
print(input.dim())

torch.Size([1, 16, 3])
3


In [5]:
input

tensor([[[0.4351, 0.8710, 0.2825],
         [0.6184, 0.0759, 0.7331],
         [0.4350, 0.1834, 0.3066],
         [0.2113, 0.4359, 0.8211],
         [0.0120, 0.7356, 0.2326],
         [0.9874, 0.7805, 0.4497],
         [0.9414, 0.3602, 0.1006],
         [0.8560, 0.0667, 0.4993],
         [0.6894, 0.6494, 0.9225],
         [0.3669, 0.6596, 0.9573],
         [0.1345, 0.8921, 0.9289],
         [0.4949, 0.9610, 0.5855],
         [0.5857, 0.0793, 0.5509],
         [0.7165, 0.0075, 0.1730],
         [0.9488, 0.3027, 0.7022],
         [0.6457, 0.0454, 0.6796]]], requires_grad=True)

In [6]:
print(output.size())
print(output.dim())

torch.Size([1, 16, 3])
3


In [7]:
output

tensor([[[1., 0., 1.],
         [0., 1., 1.],
         [1., 0., 1.],
         [1., 1., 0.],
         [1., 0., 0.],
         [1., 0., 1.],
         [0., 1., 0.],
         [1., 1., 1.],
         [0., 1., 1.],
         [0., 1., 1.],
         [0., 0., 1.],
         [0., 0., 0.],
         [1., 1., 1.],
         [1., 1., 1.],
         [0., 1., 0.],
         [1., 0., 0.]]])

In [8]:
for index, sample in enumerate(zip(input[0], output[0])):
    i, o = sample
    loss = criterion(m(i), o)
    print(i)
    print(o)
    print(loss)
    print()
    loss.backward()

tensor([0.4351, 0.8710, 0.2825], grad_fn=<SelectBackward>)
tensor([1., 0., 1.])
tensor(0.7605, grad_fn=<BinaryCrossEntropyBackward>)

tensor([0.6184, 0.0759, 0.7331], grad_fn=<SelectBackward>)
tensor([0., 1., 1.])
tensor(0.6992, grad_fn=<BinaryCrossEntropyBackward>)

tensor([0.4350, 0.1834, 0.3066], grad_fn=<SelectBackward>)
tensor([1., 0., 1.])
tensor(0.6132, grad_fn=<BinaryCrossEntropyBackward>)

tensor([0.2113, 0.4359, 0.8211], grad_fn=<SelectBackward>)
tensor([1., 1., 0.])
tensor(0.7592, grad_fn=<BinaryCrossEntropyBackward>)

tensor([0.0120, 0.7356, 0.2326], grad_fn=<SelectBackward>)
tensor([1., 0., 0.])
tensor(0.8768, grad_fn=<BinaryCrossEntropyBackward>)

tensor([0.9874, 0.7805, 0.4497], grad_fn=<SelectBackward>)
tensor([1., 0., 1.])
tensor(0.6559, grad_fn=<BinaryCrossEntropyBackward>)

tensor([0.9414, 0.3602, 0.1006], grad_fn=<SelectBackward>)
tensor([0., 1., 0.])
tensor(0.8482, grad_fn=<BinaryCrossEntropyBackward>)

tensor([0.8560, 0.0667, 0.4993], grad_fn=<SelectBackward>)
ten