In [1]:
import torch
import torch.nn as nn

In [104]:
sequence_length = 1
batch_size = 16
input_size = 30
hidden_size = 32
num_layers = 2
output_size = 1

In [105]:
input = torch.randn(sequence_length, batch_size, input_size, requires_grad=True)
target = torch.empty(batch_size, output_size, dtype=torch.long).random_(2)

In [106]:
print(input.size())
print(input.dim())

torch.Size([1, 16, 30])
3


In [108]:
input[0][0]

tensor([-1.8777, -0.3334, -1.5662, -0.0808, -0.0365, -0.3271, -0.3862,  0.2668,
        -0.9883,  0.6722, -0.0892,  0.3280,  1.5700, -1.0671, -1.1537,  1.4078,
        -0.4264, -0.0182, -1.3937,  0.4360, -0.6430, -0.2587,  0.3521,  1.3973,
        -2.0364,  1.4136, -0.3325, -0.5608,  1.1227,  0.2828],
       grad_fn=<SelectBackward>)

In [109]:
print(target.size())
print(target.dim())

torch.Size([16, 1])
2


In [110]:
target[0]

tensor([0])

In [111]:
model = nn.LSTM(input_size, hidden_size, num_layers)
h0 = torch.randn(num_layers, batch_size, hidden_size)
c0 = torch.randn(num_layers, batch_size, hidden_size)
fc = nn.Linear(hidden_size, output_size, bias = True)

In [157]:
print(model)
print(fc)
print(h0)
print(c0)

LSTM(30, 32, num_layers=2)
Linear(in_features=32, out_features=1, bias=True)
tensor([[[ 0.7377,  0.8764, -0.5866,  ...,  0.6754,  1.3995,  0.2367],
         [ 0.2613, -0.1452, -1.0952,  ..., -1.6110,  0.2815,  1.8441],
         [ 0.3309, -1.2392, -0.6172,  ...,  0.2534,  0.6707,  0.0966],
         ...,
         [ 0.0481, -1.6255, -0.2795,  ..., -0.2330, -1.5933,  0.5061],
         [-1.6779, -0.8866, -0.1682,  ..., -0.8380,  0.4171,  0.2736],
         [ 1.5782,  3.9602,  0.9542,  ...,  0.3233, -0.3171,  0.4993]],

        [[ 0.9242, -1.1199, -1.6332,  ..., -0.3369, -0.2161,  0.8712],
         [-0.9143,  0.5401, -0.1349,  ...,  1.1516, -1.9956, -1.5294],
         [-0.2596,  0.6990, -0.8146,  ...,  0.2740, -0.6808,  1.6436],
         ...,
         [ 2.0544, -1.3485,  0.7425,  ...,  0.1189,  0.3115,  1.3352],
         [-0.1102, -0.1131, -1.5930,  ...,  0.4354, -0.9153,  0.3509],
         [ 0.7128, -1.6423,  1.7793,  ...,  0.7111,  0.3158, -0.1537]]])
tensor([[[ 1.1847,  0.0457, -0.3079,  .

In [142]:
output, hidden = model(input, (h0, c0))
output_fc = fc(output)
output_fc_0 = fc(output[:, -1, :]) # 마지막 출력층

In [149]:
print(output.size())
print(output_fc.size())
print(output_fc_0.size()) # 마지막 출력층

torch.Size([1, 16, 32])
torch.Size([1, 16, 1])
torch.Size([1, 1])


In [156]:
print(output_fc[0])

tensor([[ 0.1977],
        [ 0.0478],
        [ 0.1320],
        [ 0.1741],
        [ 0.0411],
        [ 0.1366],
        [ 0.0723],
        [ 0.0991],
        [ 0.0963],
        [ 0.0110],
        [-0.0305],
        [ 0.1622],
        [ 0.2297],
        [ 0.3120],
        [ 0.1111],
        [ 0.1551]], grad_fn=<SelectBackward>)


In [133]:
print(output_fc[0].view(1, -1))


tensor([[ 0.1977,  0.0478,  0.1320,  0.1741,  0.0411,  0.1366,  0.0723,  0.0991,
          0.0963,  0.0110, -0.0305,  0.1622,  0.2297,  0.3120,  0.1111,  0.1551]],
       grad_fn=<ViewBackward>)


In [122]:
criterion = nn.CrossEntropyLoss()

In [134]:
loss = criterion(output_fc[0].view(1, -1), target[0])

In [135]:
loss

tensor(2.7001, grad_fn=<NllLossBackward>)